<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LanguageSelector'              => __DIR__ . '/src/LanguageSelector/class.LanguageSelector.php',
    'LanguageSelectorException'     => __DIR__ . '/src/LanguageSelector/class.LanguageSelector.php',
);