<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'KryuuLanguageSelector'     => __DIR__ . '/src/KryuuLanguageSelector/KryuuLanguageSelector.php',
    'KryuuLanguageSelector'     => __DIR__ . '/src/KryuuLanguageSelector/KryuuLanguageSelector.php',
);